### PR TITLE
MSL:  convert depth buffer fetch to regular texture read.

### PR DESCRIPTION
**Pull request by atyuwen**
Metal doesn't support depth buffer fetch, so here gives a chance to convert those subpassLoads from depth buffer to regular texture reads.

### CODE REVIEW

**Comment by HansKristian-Work** [comment]
I don't really understand what this is trying to solve. Please add some tests.

**Comment by cdavis5e** [comment]
> I don't really understand what this is trying to solve.

I suspect it's for when a depth `SubpassInput` is used with `use_framebuffer_fetch_subpasses`. Metal can't yet do framebuffer fetch with a D/S attachment.

**Comment by atyuwen** [comment]
> > I don't really understand what this is trying to solve.
> 
> I suspect it's for when a depth `SubpassInput` is used with `use_framebuffer_fetch_subpasses`. Metal can't yet do framebuffer fetch with a D/S attachment.

Exactly. Unfortunately in standard Vulkan GLSL there is no way to distinguish whether a `SubpassInput` is depth or not. This pr currently uses `SPIRType.image.depth` to specify a depth `SubpassInput`, and assumes it's the SPIR-V codegen's responsibility to set the `SPIRType.image.depth` field correctly.

However, the `SPIRType.image.depth`  field is always `false` if the SPIR-V is generated by Glslang, which makes it hard to write a unit test. I'm considering whether it is better to add an interface like `CompilerMSL::mark_depth_subpass_input(VariableID id)` to specify a depth `SubpassInput`, though the implementation will be slightly more complicated.

**Comment by HansKristian-Work** [comment]
Subpass attachments in Vulkan do not know if the attachment is depth or not, so yes, we will need some way to mark if an input_attachment_location is depth or not.

**Comment by atyuwen** [comment]
Ok, finally I realized it might be an improper feature because subpassInput can be passed as function arguments. for example, the following function can be called with a color subpassInput and also depth subpassInput.
```
vec4 load_subpasses(mediump subpassInput uInput)
{
	return subpassLoad(uInput);
}
```
To handle it correctly, the compiler must generate 2 overloads: one for color subpassInput and one for depth subpassInput respectively, which makes things too complicated.

**Pull request closed without merging**
