### PR TITLE
Handle exponential explosion of code-gen during first phase of compile and fix CFG dominator checks.

### LINKED ISSUE #374: Exponentially growing redundant code on combinations of swizzles
If a shader performs combinations of consecutive swizzles, the code generated grows exponentially, as swizzle expressions are embedded in others.

For example...the code below was generated in MSL from a shader with 3 stages of swizzles and math. Code grows exponentially by a power-of-four! Another combination that involves 9 stages resulted in 10MB of generated code!

The human-readable `SPIR-V` that generated this code can be found in this file: [swizzle-heavy-shader.spv.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/1591935/swizzle-heavy-shader.spv.txt).

I'm wondering if a solution might be to force temporary variables to be generated for each swizzle combination. Would that make sense? I'm not sure how to cause that to happen.

@HansKristian-ARM  Any thoughts?

```
_6436._m0 = float4((float4((float4((float4(0.0).xyz + (_7719 * 0.5)).x, 
                                   (float4(0.0).xyz + (_7719 * 0.5)).y, 
                                   (float4(0.0).xyz + (_7719 * 0.5)).z, 
                                   float4(0.0).w).xyz + (_7720 * 0.5)).x,
                            (float4((float4(0.0).xyz + (_7719 * 0.5)).x, 
                                    (float4(0.0).xyz + (_7719 * 0.5)).y, 
                                    (float4(0.0).xyz + (_7719 * 0.5)).z,
                                     float4(0.0).w).xyz + (_7720 * 0.5)).y,
                            (float4((float4(0.0).xyz + (_7719 * 0.5)).x, 
                                    (float4(0.0).xyz + (_7719 * 0.5)).y, 
                                    (float4(0.0).xyz + (_7719 * 0.5)).z,
                                     float4(0.0).w).xyz + (_7720 * 0.5)).z,
                            float4((float4(0.0).xyz + (_7719 * 0.5)).x, 
                                   (float4(0.0).xyz + (_7719 * 0.5)).y, 
                                   (float4(0.0).xyz + (_7719 * 0.5)).z,
                                    float4(0.0).w).w).xyz + (_7721 * 0.75)).x,
                   (float4((float4((float4(0.0).xyz + (_7719 * 0.5)).x, 
                                   (float4(0.0).xyz + (_7719 * 0.5)).y, 
                                   (float4(0.0).xyz + (_7719 * 0.5)).z, 
                                   float4(0.0).w).xyz + (_7720 * 0.5)).x,
                           (float4((float4(0.0).xyz + (_7719 * 0.5)).x, 
                                   (float4(0.0).xyz + (_7719 * 0.5)).y, 
                                   (float4(0.0).xyz + (_7719 * 0.5)).z, 
                                    float4(0.0).w).xyz + (_7720 * 0.5)).y,
                           (float4((float4(0.0).xyz + (_7719 * 0.5)).x, 
                                   (float4(0.0).xyz + (_7719 * 0.5)).y, 
                                   (float4(0.0).xyz + (_7719 * 0.5)).z, 
                                    float4(0.0).w).xyz + (_7720 * 0.5)).z,
                            float4((float4(0.0).xyz + (_7719 * 0.5)).x, 
                                   (float4(0.0).xyz + (_7719 * 0.5)).y, 
                                   (float4(0.0).xyz + (_7719 * 0.5)).z,
                                    float4(0.0).w).w).xyz + (_7721 * 0.75)).y,
                   (float4((float4((float4(0.0).xyz + (_7719 * 0.5)).x, 
                                   (float4(0.0).xyz + (_7719 * 0.5)).y, 
                                   (float4(0.0).xyz + (_7719 * 0.5)).z, 
                                    float4(0.0).w).xyz + (_7720 * 0.5)).x,
                           (float4((float4(0.0).xyz + (_7719 * 0.5)).x, 
                                   (float4(0.0).xyz + (_7719 * 0.5)).y, 
                                   (float4(0.0).xyz + (_7719 * 0.5)).z, 
                                    float4(0.0).w).xyz + (_7720 * 0.5)).y,
                           (float4((float4(0.0).xyz + (_7719 * 0.5)).x, 
                                   (float4(0.0).xyz + (_7719 * 0.5)).y, 
                                   (float4(0.0).xyz + (_7719 * 0.5)).z, 
                                    float4(0.0).w).xyz + (_7720 * 0.5)).z,
                            float4((float4(0.0).xyz + (_7719 * 0.5)).x, 
                                   (float4(0.0).xyz + (_7719 * 0.5)).y, 
                                   (float4(0.0).xyz + (_7719 * 0.5)).z,
                                    float4(0.0).w).w).xyz + (_7721 * 0.75)).z,
                    float4((float4((float4(0.0).xyz + (_7719 * 0.5)).x, 
                                   (float4(0.0).xyz + (_7719 * 0.5)).y, 
                                   (float4(0.0).xyz + (_7719 * 0.5)).z, 
                                    float4(0.0).w).xyz + (_7720 * 0.5)).x,
                           (float4((float4(0.0).xyz + (_7719 * 0.5)).x, 
                                   (float4(0.0).xyz + (_7719 * 0.5)).y, 
                                   (float4(0.0).xyz + (_7719 * 0.5)).z, 
                                    float4(0.0).w).xyz + (_7720 * 0.5)).y,
                           (float4((float4(0.0).xyz + (_7719 * 0.5)).x, 
                                   (float4(0.0).xyz + (_7719 * 0.5)).y, 
                                   (float4(0.0).xyz + (_7719 * 0.5)).z, 
                                    float4(0.0).w).xyz + (_7720 * 0.5)).z,
                            float4((float4(0.0).xyz + (_7719 * 0.5)).x, 
                                   (float4(0.0).xyz + (_7719 * 0.5)).y, 
                                   (float4(0.0).xyz + (_7719 * 0.5)).z,
                                    float4(0.0).w).w).w);
```

### LINKED ISSUE #409: Declaring a constant buffer struct with the name of the constant buffer instead of the struct
I have this SPIR-V

[DEFERREDLIGHTPS_OPTIMIZED.TXT](https://github.com/KhronosGroup/SPIRV-Cross/files/1661206/DEFERREDLIGHTPS_OPTIMIZED.TXT)

that ends up producing code like the following:

```glsl
void main()
{
    float _4855;
    vec4 _4849;
    float _1956;
    vec3 _2333;
    vec3 _2374;
    float _2468;
    vec3 _3297;
    vec3 _3296;
    g_Light_CB _4842;
    vec3 _2504;
    float _2518;
    vec4 _4851;
```

Notice how variable _4842 is being declared as g_Light_CB instead of just Light.

### LINKED ISSUE #410: Still getting undeclared variable issues
For an example of this, see

[DEFERREDRENDERSSRPS_OPTIMIZED.TXT](https://github.com/KhronosGroup/SPIRV-Cross/files/1661243/DEFERREDRENDERSSRPS_OPTIMIZED.TXT)

Variable _3209 is being used without being declared

### PR DESCRIPTION
**Pull request by HansKristian-ARM**
Certain patterns with OpVectorShuffle (and probably others) will cascade
to so large, that they can cause OOM. After we have observed
force_recompile, don't spend unnecessary memory emitting code which will
never be used.

Fixes #374.

Also fixes a recent regression w.r.t. temporaries and dominator checks. Way too many temporaries were created causing some issues.

Fixes #409.
Fixes #410.

### CODE REVIEW

**Comment by HansKristian-ARM** [comment]
@billhollings This fixes the OOM issue you had, if you're okay with it, I think we can roll with this.

**Comment by billhollings** [comment]
Sorry for taking so long to respond...#407 was stopping me from updating and testing against latest.

**Comment by billhollings** [comment]
Yes...this fixes the OOM issue...and is good to go.

However...the `asm/frag/vector-shuffle-oom.asm.frag` tests fail when merged with the latest SPIRV-Cross.

**Comment by HansKristian-ARM** [comment]
Ok, I'll try rebasing and run another test. This Travis run is outdated.

**Comment by HansKristian-ARM** [comment]
Linux passed.

**Pull request merged**
