### PR TITLE
Implement dead variable elimination.

### PR DESCRIPTION
**Pull request by HansKristian-ARM**
Adds a way to remove unused variables from consideration in reflection and cross-compilation. Example:

```
auto active = compiler->get_active_interface_variables();
res = compiler->get_shader_resources(active);
compiler->set_enabled_interface_variables(move(active));
```

### CODE REVIEW

**Comment by hiddenbitious** [comment]
That was super quick :)

Tried a quick test with a couple of trivial shaders and seems to work fine. Redundant variable is still registered though in the generated .cpp, but I think that this is a minor issue, as it will never be used in shader.

```
                VertexResources::init(s);
                s.register_stage_input(a_pos__, 0);
                s.register_stage_input(a_pos2__, 0);

```

**Comment by HansKristian-ARM** [comment]
Sounds trivial to fix.

**Comment by HansKristian-ARM** [comment]
It seems to work for me. --remove-unused-variables removed dead variables for me in C++.

**Comment by hiddenbitious** [comment]
Sorry my mistake. I merged in a local branch that had some conflicting changes. Works good.

**Pull request merged**
