### PR TITLE
Fixing HLSL compiler resource binding remap bug

### PR DESCRIPTION
**Pull request by jojon5**

### CODE REVIEW

**Comment by HansKristian-Work** [comment]
Are you sure this is a bug? The check is supposed to be inverted.

**Review by HansKristian-Work — CHANGES_REQUESTED** [review]
I don't think this change is correct. The check currently is essentially `if (autobinding == 0) { use_explicit_binding() } else { let_hlsl_compiler_decide() }`. It might be a bit confusing since the check is inverted, so a clarifying comment instead would be appropriate.

**Comment by jojon5** [comment]
Not sure, I was hoping to get clarification on the bug I was seeing in my app. This change solved my problem. But I suppose it could possibly be my application incorrectly configuring the compiler object (or the bug is somewere else)

**Comment by HansKristian-Work** [comment]
If you want to let the HLSL compiler decide on bindings for you, i.e., you reflect the resulting DXBC yourself, then you need to add the AUTO flags to the compiler first, otherwise, the bindings will come directly from the SPIR-V.

**Comment by HansKristian-Work** [comment]
Closing this. If you have further issues on HLSL autobinding, you can open an issue.

**Pull request closed without merging**
