### PR TITLE
Added install targets to cmake.

### PR DESCRIPTION
**Pull request by biojppm**
The install targets were added for each of the libraries and executable. I created separate per-library config export files. Let me know if you think this needs adjustment, or if you are not confortable with the names I used (there is an ambiguity with the dash and underscore separators).

See the tree below, which is the result of a Release install on Windows:

```
./bin/spirv-cross.exe
./include/spirv_cross/GLSL.std.450.h
./include/spirv_cross/spirv.hpp
./include/spirv_cross/spirv_cfg.hpp
./include/spirv_cross/spirv_common.hpp
./include/spirv_cross/spirv_cpp.hpp
./include/spirv_cross/spirv_cross.hpp
./include/spirv_cross/spirv_glsl.hpp
./include/spirv_cross/spirv_msl.hpp
./lib/spirv-cross-core.lib
./lib/spirv-cross-cpp.lib
./lib/spirv-cross-glsl.lib
./lib/spirv-cross-msl.lib
./share/spirv_cross_core/cmake/spirv_crossConfig-release.cmake
./share/spirv_cross_core/cmake/spirv_crossConfig.cmake
./share/spirv_cross_cpp/cmake/spirv_cross_cppConfig-release.cmake
./share/spirv_cross_cpp/cmake/spirv_cross_cppConfig.cmake
./share/spirv_cross_glsl/cmake/spirv_cross_glslConfig-release.cmake
./share/spirv_cross_glsl/cmake/spirv_cross_glslConfig.cmake
./share/spirv_cross_msl/cmake/spirv_cross_mslConfig-release.cmake
./share/spirv_cross_msl/cmake/spirv_cross_mslConfig.cmake
```

### CODE REVIEW

**Comment by HansKristian-ARM** [comment]
Ping, the CLA needs to be signed before this can be merged.

**Comment by biojppm** [comment]
Sorry for the delay. Kept putting this off as I had to rebase my commits because the email was wrong. CLA now is working; if the tests pass all should be fine.

**Comment by HansKristian-ARM** [comment]
Can you rebase this branch on current master? This base branch is really old.

**Comment by biojppm** [comment]
@HansKristian-ARM As it is the PR is merged with current master. Could you clarify?

**Comment by HansKristian-ARM** [comment]
It is merged, but the merge commit is against a very old master, which I would like to avoid if possible. I would prefer if you could run `git rebase <remote>/master` and push that up to your branch to keep a more linear history when it is merged.

**Comment by HansKristian-ARM** [comment]
I rebased manually on a different PR and merged it. Sorry for the long delay.

**Pull request closed without merging**
