### PR TITLE
CompilerMSL support and tests for OpUndef.

### PR DESCRIPTION
**Pull request by billhollings**
Changes outside `spirv_msl.hpp/cpp` are result of running `format_all.sh`.

### CODE REVIEW

**Comment by HansKristian-ARM** [comment]
It seems like we have mismatching clang-format versions, mine is on 5.0.0 at least.

**Comment by billhollings** [comment]
Thanks.

I've upgraded to `clang-format 5.0.0` now.

I wonder if there is a way of validating or enforcing the minimum `clang-format` version within `format_all.sh`...to avoid successive submissions flipping the formatting back and forth as different submitters drift versions of `clang-format` over time.

**Comment by HansKristian-ARM** [comment]
Right, I'm a bit concerned that putting some mandate on the clang-format would drive potential contributors away. I'm on Arch, so I always have the bleeding edge stuff, but not everyone will have that. I suppose I could look into adding some kind of warning at least when running ./format_all.sh and try to keep that up-to-date.

**Comment by billhollings** [comment]
Hmmm...is it possible to run `format_all.sh` on the server during a pull request submission (like Travis, etc)...and avoid devs having to think about it at all?

**Comment by HansKristian-ARM** [comment]
This implies that TravisCI is able to magically modify the commit in question ... I doubt that is possible or practical.

**Pull request merged**
