### PR TITLE
Overhaul buffer packing in HLSL and GLSL

### LINKED ISSUE #302: Support for packoffset in the HLSL backend
Shader Model 4.0 seems to support explicit offsets in constant buffers with the [packoffset][1] keyword. It would be great if SPIRV-Cross could use this to replicate the UBO layout from the input SPIR-V. That way, code that uses the shader could use the same buffer layout for GLSL and HLSL targets.

One issue is that I think this will require removing the intermediate struct that SPIRV-Cross emits for UBOs, since packoffset only works on direct members of the cbuffer definition.

[1]: https://msdn.microsoft.com/en-us/library/windows/desktop/dd607358.aspx

### PR DESCRIPTION
**Pull request by HansKristian-ARM**
This is a fairly large change to support:
- GL_ARB_enhanced_layouts in GLSL to better support HLSL packing patterns.
- HLSL cbuffer code has been overhauled to support packoffset to better support std140 layouts.
- row_major/column_major is now declared in HLSL which should remove most issues with having to magically transpose matrices. (This needs more testing ...)
- Validation that the std140 fallback layout actually works. An error will be thrown if neither std140 nor std430 is possible as a buffer layout.
- To support packoffset, the cbuffer struct is flattened, so no more dummy struct outside the cbuffer declaration.

Closes #302,
Progresses #295.

### CODE REVIEW

**Comment by HansKristian-ARM** [comment]
@rossy please give it a spin.

**Comment by rossy** [comment]
Hmm, I get an error: undeclared identifier '_22_m0'

Full mpv output is as follows (includes raw GLSL and HLSL shader source, plus error output from D3DCompile()):
https://gist.github.com/rossy/55f71c4d6e03d0bcd7fd54d53047604a

**Comment by HansKristian-ARM** [comment]
Ah, right ... Some silly cases with stripped SPIR-V modules, will fix.

**Comment by HansKristian-ARM** [comment]
@rossy should work now.

**Comment by rossy** [comment]
Yep, this appears to work for our shaders. Nice work.

**Pull request merged**
