### PR TITLE
Proper types for sampled images in HLSL4/5

### PR DESCRIPTION
**Pull request by RobDangerous**
Fixes passing to functions,...

### CODE REVIEW

**Comment by HansKristian-ARM** [comment]
Using a struct to represent combined image samplers seems like the cleanest approach, but I'm a bit worried that this will not work in all cases.

Can you use `: register(t#)` and ` : register(s#)` for the texture and sampler in those structs?

How will combining the image and sampler work? Can you build a structure safely from a standalone Texture2D and SamplerState and use that to sample an image?

**Comment by RobDangerous** [comment]
No luck with register declarations according to https://msdn.microsoft.com/en-us/library/windows/desktop/dn899207(v=vs.85).aspx
Have to flatten it. Should I wait for your other pull request?

**Comment by HansKristian-ARM** [comment]
I will continue on that PR soon-ish. It is also needed to sort out some corner cases with shadow samplers as well, so I suggest we go with that approach instead.

**Comment by RobDangerous** [comment]
Okidoki!

**Comment by HansKristian-ARM** [comment]
Unfortunate about the duplicated work, but oh well.

**Pull request closed without merging**
