### PR TITLE
Revert "Do not disable temporary forwarding when we suppress usage tracking"

### PR DESCRIPTION
**Pull request by dnovillo**
This reverts commit 18bcc9b79077fe179318f607d348ff35afd24f6a.

This is a temporary workaround to address the performance slowdown
reported in https://github.com/KhronosGroup/SPIRV-Cross/issues/1108.

Tested with `./test_shaders.sh` and confirmed that compile times are back to 40ms for the test case in #1108.

### CODE REVIEW

**Comment by HansKristian-Work** [comment]
Try reverting just this branch: https://github.com/KhronosGroup/SPIRV-Cross/pull/1109/files#diff-09b7cdf207013ada0b4e38970bc27158L7553. That might be it.

**Comment by dnovillo** [comment]
> Try reverting just this branch: https://github.com/KhronosGroup/SPIRV-Cross/pull/1109/files#diff-09b7cdf207013ada0b4e38970bc27158L7553. That might be it, or, hmm. Maybe not.

No, that was the first branch I reverted when initially tracking this down.  It was not it.  I believe that the new `suppressed_usage_tracking` set caused the slowdown.  The hashing functions in these sets is now overwhelming.

I have not noticed any regressions after this commit.  I'll try applying it locally because I don't really know this codebase and a principled fix would take more cycles than I have available.

**Comment by HansKristian-Work** [comment]
Fair enough, it does seem like there is a problem where invalidate ID can be called over and over again on the same ID, which then trickles down to all expression dependencies recursively, and certain pathological shaders would explode in compile time. I guess I'll spend a little time on this tomorrow after all.

**Comment by dnovillo** [comment]
> Fair enough, it does seem like there is a problem where invalidate ID can be called over and over again on the same ID, which then trickles down to all expression dependencies recursively, and certain pathological shaders would explode in compile time. I guess I'll spend a little time on this tomorrow after all.

Thanks!

**Comment by HansKristian-Work** [comment]
Fixed it now (almost 10x faster for me compared to before the performance regression).

**Comment by dnovillo** [comment]
> Fixed it now (almost 10x faster for me compared to before the performance regression). The performance bug was always there.

Excellent.  Thanks for the quick fix!

**Pull request closed without merging**
