### PR TITLE
Check if a loop variable candidate is actually used.

### LINKED ISSUE #407: Recent changes have introduced OpPhi initialization issue
Recent changes (within the most recent 18 commits) have introduced an issue with OpPhi handling in certain circumstances.

           %7404 = OpPhi %13 %15154 %22801 %11264 %9010

causes the following MSL to be omitted:

            float _7404 = _0;

which of course fails compilation because of the `_0`.

This did not happen before.

The SPIR-V that causes this is: 
[OpPhiBug.spv.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/1657112/OpPhiBug.spv.zip)

The full log of the conversion is: 
[OpPhiBugLog.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/1657108/OpPhiBugLog.txt)

### PR DESCRIPTION
**Pull request by HansKristian-ARM**
Phi nodes used in continue blocks are not always loop variables.
Fix by checking if path from dominator to loop header has some variable use.
Add test for false loop init.
Clean up how for loop variables are declared. Missing initializers or OpUndef initialized variables (why ...) will be declared outside the for loop header.

Fix #407.

### CODE REVIEW

**Comment by billhollings** [comment]
@HansKristian-ARM 

Will you be merging this? Or are you waiting for further testing?

**Comment by HansKristian-ARM** [comment]
@billhollings Waiting for Travis OSX build to start since this might affect MSL. If you can verify it passes on your end I can merge. Travis OSX is really slow lately (3-4 days to do a run :().

**Comment by billhollings** [comment]
Sure...I'll test it on my end now. Thanks.

**Comment by billhollings** [comment]
All looks good.this PR fixes the initial problem reported.`test_shaders.sh` runs perfectly.

**Comment by HansKristian-ARM** [comment]
Alright, I'll merge :)

**Comment by billhollings** [comment]
Thanks for fixing this so quickly!

**Pull request merged**
