### PR TITLE
CompilerMSL add support for texel buffers.

### PR DESCRIPTION
**Pull request by billhollings**
Compiler MSL support DimBuffer as image dimension.
CompilerMSL check texture coordinate result type dimension before adding swizzles.
Update MSL reference shaders affected by this update.

### CODE REVIEW

**Comment by billhollings** [comment]
@HansKristian-ARM 

Would you mind having a look at the failed Travis build on `shaders-msl/frag/mix.frag` please?

There seems to be some platform-dependent misery going on here with `emit_mix_op()` statements.

Under OSX, the MSL shader is generated as in the `reference/shaders-msl/frag/mix.frag` file...with nice clean `?:` ternary statements everywhere. On the other hand, Travis is generating [this mess](https://travis-ci.org/KhronosGroup/SPIRV-Cross/jobs/200077036#L1441), which seems to be a combination of ternary and temp-var-based `if()` statements.

I've tried following the logic of `emit_mix_op()`...but I can't see any reason why the code would not always emit a nice ternary operator...and since it always does in my OSX environment, I am not able to effectively debug what's going on under the Travis environment.

**Comment by HansKristian-ARM** [comment]
Will have a look tomorrow.

**Comment by HansKristian-ARM** [comment]
Ok, I also get the if branchy variant. I think you're not using the same glslang checkout that the Travis script uses. It seems like that glslang version in Travis does not optimize the mix statements properly while perhaps your recent checkout does.

It probably makes sense to update the glslang revision now in the travis script and update all the reference shaders along with it.

**Comment by HansKristian-ARM** [comment]
Indeed, it's a new glslang ... I'll update Travis to use latest glslang, it uncovered a lingering bug in emit_mix_op anyways.

**Comment by HansKristian-ARM** [comment]
Merged it. Please see .travis.yml for the exact commit Travis is using for glslang.

**Comment by billhollings** [comment]
@HansKristian-ARM 

Thanks for the fix. Travis is happy with this pull request now.

**Pull request merged**
