### PR TITLE
Update to latest glslang/SPIRV-Tools.

### PR DESCRIPTION
**Pull request by fjhenigman**

### CODE REVIEW

**Comment by HansKristian-Work** [comment]
Any particular reason for this update other than staying up-to-date with master?

**Comment by fjhenigman** [comment]
> Any particular reason for this update other than staying up-to-date with master?

I need to roll spirv-tools in shaderc to pick up a fix, but then shaderc's spirv-cross wrapper (which I test with the spirv-cross tests) fails, so I need to update the spirv-cross tests.

Is there a reason not to do this update?

Thanks.

**Comment by HansKristian-Work** [comment]
That makes sense. I see there's some change in the reference files. I'll investigate that tomorrow.

**Comment by fjhenigman** [comment]
Appreciate the quick merge!  Makes my life easier.

**Pull request merged**
