### PR TITLE
adds Khronos license to LICENSES folder.

### PR DESCRIPTION
**Pull request by Keenuts**
This license is in spirv.h, but absent from the LICENSES file.

### CODE REVIEW

**Comment by HansKristian-Work** [comment]
@oddhack Is this something you need to look at?

**Comment by oddhack** [comment]
> @oddhack Is this something you need to look at?

I suggest using a more qualified SPDX identifier (LicenseRef-KhronosFreeUse? I'm not sure what we actually call this specific MIT variant or indeed if we have a formal name for it).

Otherwise, it looks like this (whitespace changes aside) is just putting a copy of the license statement in LICENSES/ as REUSE requires, which is good. You could make the headers a bit shorter by replacing the full license text with '// SPDX-License-Identifier: LicenseRef-Khronos\<whatever>'. But that would probably require corresponding changes in the generator scripts, which I think are in another repo, so best to leave that complication for another PR.

**Comment by Keenuts** [comment]
Thanks for looking into that 😊

> I suggest using a more qualified SPDX identifier (LicenseRef-KhronosFreeUse? I'm not sure what we actually call this specific MIT variant or indeed if we have a formal name for it).

done!


> Otherwise, it looks like this (whitespace changes aside)
Is the whitespace change an issue? (Just thought I'd clean this at the same occasion)

**Comment by oddhack** [comment]
> Thanks for looking into that blush
> 
> > I suggest using a more qualified SPDX identifier (LicenseRef-KhronosFreeUse? I'm not sure what we actually call this specific MIT variant or indeed if we have a formal name for it).
> 
> done!
> 
> > Otherwise, it looks like this (whitespace changes aside)
> > Is the whitespace change an issue? (Just thought I'd clean this at the same occasion)

I'm not very familiar with the SPIR repository ecosystem but I had the impression that this header is generated elsewhere and copied in here, so any local changes could be overwritten eventually? If not then it's not an issue.

**Review by oddhack — APPROVED** [review]

**Comment by Keenuts** [comment]
>  Ahh yes, probably copied from SPIRV-Headers.
Reverting this so it's clean.

**Pull request merged**
