### PR TITLE
add `matrix` to the list of illegal names.

### PR DESCRIPTION
**Pull request by aliaspider**

### CODE REVIEW

**Comment by pmuetschard** [comment]
May I ask why? "matrix" is not a reserved keyword in glsl...

**Comment by aliaspider** [comment]
`CompilerHLSL` inherits `replace_illegal_names` from `CompilerGLSL`

**Comment by billhollings** [comment]
Should we think about separating the lists per backend via a virtual population function?

`CompilerGLSL` could create the base list...and then each subclass could add or subtract specific platform requirements.

**Comment by HansKristian-ARM** [comment]
We certainly could if people feel it's important. PR welcome.

**Comment by pmuetschard** [comment]
#565 PR delivered

**Pull request merged**
